### ISSUE TITLE
Using a session token or aws .credentials file?

### ISSUE THREAD

**Issue by bildungsroman** [assignar/react-aws-dashboard-codepipeline#1]
I love this idea, but can't get it to work on my machine. I use an `aws_session_token` to authenticate, but adding `config.sessionToken = "...my token";` to `App.tsx` does not work.

Is there a way to use a session token, or better yet, a local profile from my `.aws/credentials` file?

**Comment by c-py** [comment]
Hey. 
I just succesfully tested with the following configuration:

```typescript
const App: React.FC = () => {
  const config = new AWS.Config();
  config.accessKeyId = "... access key";
  config.secretAccessKey = "... secret access key";
  config.sessionToken = "... session token";
  config.region = "ap-southeast-2";

  return <Environment name="Test" config={config} />;
};
```

I think a session token should work (provided the session is not expired). Are you able to make SDK calls with your current AWS Config? 
e.g.

```typescript
import React from "react";
import AWS from "aws-sdk";

const App: React.FC = () => {
  const config = new AWS.Config();
  config.accessKeyId = "... access key";
  config.secretAccessKey = "... secret access key";
  config.sessionToken = "... session token";
  config.region = "ap-southeast-2";

  const sts = new AWS.STS(config)
  sts.getCallerIdentity({}, (err, data) => {
    if (err) alert(JSON.stringify(err)); // an error occurred
    else alert(JSON.stringify(data))
  })
  return <></>
};

export default App;
```

Regarding loading from `.aws/credentials`. It sounds useful, however I don't know if it is possible when using a the AWS SDK in a browser.

**Comment by c-py** [comment]
Closing this issue as there was no further conversation.
